// The wire format, asserted against the same fixtures the Go daemon writes.
//
// The rest of this suite runs against fake-daemon.js and never against the real
// binary, so nothing in it would notice the Go side renaming a field. That gap
// shipped once already: a renamed response field left callers receiving no
// cookies at all, with no error and no warning, while every gate was green.
//
// These fixtures are generated by:
//     go test ./daemon/ -run TestProtocolFixture -update
// If one of these tests fails, the protocol changed — fix the client or change
// the protocol deliberately, but do not regenerate the fixture to make the test
// pass.

import assert from 'node:assert/strict';
import { test } from 'node:test';
import { chmodSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { Client } from '../index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixtures = path.join(here, '..', '..', 'testdata', 'protocol');
const fakeDaemon = path.join(here, 'fake-daemon.js');

const load = (name) => JSON.parse(readFileSync(path.join(fixtures, name), 'utf8'));

// The fake is injected as the binary, the same way client.test.js does it, so
// the fixture travels the real spawn/pipe/readline path rather than being
// handed straight to a parser.
const wrapperDir = mkdtempSync(path.join(os.tmpdir(), 'tls-forge-protocol-'));
const configuredDaemon = process.env.TLSFORGE_TEST_DAEMON;
let wrapper;
if (configuredDaemon) {
  wrapper = path.resolve(configuredDaemon);
} else if (process.platform === 'win32') {
  throw new Error('TLSFORGE_TEST_DAEMON must name the native fake daemon on Windows');
} else {
  wrapper = path.join(wrapperDir, 'wrapper.sh');
  writeFileSync(wrapper, `#!/bin/sh\nexec "${process.execPath}" "${fakeDaemon}" "$@"\n`);
  chmodSync(wrapper, 0o755);
}

test('the committed wire format parses', async () => {
  const client = new Client({ binary: wrapper });
  try {
    const response = await client.get('https://fixture/');
    assert.equal(response.status, 200);
    assert.equal(response.url, 'https://example.com/after-redirect');
    assert.deepEqual(response.content, Buffer.from([0x00, 0xfe, 0xff, 0x80]));
    assert.deepEqual(response.headers['content-type'], ['text/html; charset=utf-8']);
    assert.deepEqual(response.headers['set-cookie'], ['a=1', 'b=2']);
    // The field whose rename went unnoticed.
    assert.deepEqual(response.cookies, ['a=1', 'b=2']);
  } finally {
    await client.close();
  }
});

test('every response field is one this client reads', () => {
  assert.deepEqual(Object.keys(load('response.json')).sort(), [
    'body',
    'bodyEncoding',
    'cookies',
    'headers',
    'id',
    'status',
    'url',
  ]);
});

test('the request fixture is the shape this client sends', () => {
  const request = load('request.json');
  assert.deepEqual(Object.keys(request).sort(), [
    'body',
    'bodyEncoding',
    'headers',
    'id',
    'method',
    'order',
    'setCookie',
    'url',
  ]);
  assert.equal(request.bodyEncoding, 'base64');
  assert.deepEqual(
    Buffer.from(request.body, 'base64'),
    Buffer.from([0x00, 0xfe, 0xff, 0x80]),
  );
});
