package cookie

import (
	"strings"
	"testing"
	"time"
)

// curlWrote is a real cookies.txt, produced by curl against a server that set
// two cookies. Kept verbatim, because interoperability with the file everything
// else reads is the whole point of supporting this format.
const curlWrote = "# Netscape HTTP Cookie File\n" +
	"# https://curl.se/docs/http-cookies.html\n" +
	"# This file was generated by libcurl! Edit at your own risk.\n" +
	"\n" +
	"127.0.0.1\tFALSE\t/\tFALSE\t0\ttier\tgold\n" +
	"#HttpOnly_127.0.0.1\tFALSE\t/\tTRUE\t0\tvisitor\t42\n"

func TestLoadWhatCurlWrote(t *testing.T) {
	file, err := Load([]byte(curlWrote))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(file.Sets) != 1 || len(file.Sets[0].Cookies) != 2 {
		t.Fatalf("sets: %+v", file.Sets)
	}

	byName := map[string]Cookie{}
	for _, c := range file.Sets[0].Cookies {
		byName[c.Name] = c
	}

	// The prefix reads like a comment and is not one. A parser that skips every
	// line beginning with # drops exactly the cookies that matter most.
	if got := byName["visitor"]; !got.HTTPOnly || !got.Secure || got.Value != "42" {
		t.Errorf("visitor: %+v", got)
	}
	if got := byName["tier"]; got.HTTPOnly || got.Secure || got.Value != "gold" {
		t.Errorf("tier: %+v", got)
	}
	// Zero is how this format spells a session cookie: no date, rather than a
	// date in 1970.
	if !byName["tier"].Expires.IsZero() {
		t.Errorf("a session cookie was given a date: %v", byName["tier"].Expires)
	}
	if byName["visitor"].Domain != "127.0.0.1" {
		t.Errorf("domain: %q", byName["visitor"].Domain)
	}
}

func TestLoadNetscapeDetails(t *testing.T) {
	file, err := Load([]byte(
		"# a comment\n" +
			"\n" +
			".example.com\tTRUE\t/app\tTRUE\t1893456245\tsession\tabc=with=equals\n"))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	got := file.Sets[0].Cookies[0]
	if got.Domain != ".example.com" || got.Path != "/app" || !got.Secure {
		t.Errorf("got %+v", got)
	}
	if got.Expires.Unix() != 1893456245 {
		t.Errorf("expiry = %v", got.Expires)
	}
	// A value may hold anything the line can, separators included.
	if got.Value != "abc=with=equals" {
		t.Errorf("value = %q", got.Value)
	}
}

func TestLoadNetscapeRejectsWhatItCannotRead(t *testing.T) {
	for _, tc := range []struct{ name, body string }{
		{"too few fields", "example.com\tTRUE\t/\tFALSE\t0\tname\n"},
		{"an expiry that is not a number", "example.com\tTRUE\t/\tFALSE\tsoon\tname\tvalue\n"},
		{"a cookie with no name", "example.com\tTRUE\t/\tFALSE\t0\t\tvalue\n"},
		{"comments and nothing else", "# Netscape HTTP Cookie File\n# nothing here\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := Load([]byte(tc.body)); err == nil {
				t.Error("no error")
			}
		})
	}
}

func TestEncodeNetscape(t *testing.T) {
	set := Set{Cookies: []Cookie{
		{Name: "tier", Value: "gold", Domain: "127.0.0.1", Path: "/"},
		{Name: "visitor", Value: "42", Domain: "127.0.0.1", Path: "/",
			Secure: true, HTTPOnly: true},
	}}
	written := string(set.EncodeNetscape())

	// The same two lines curl writes for the same two cookies.
	for _, want := range []string{
		"127.0.0.1\tFALSE\t/\tFALSE\t0\ttier\tgold\n",
		"#HttpOnly_127.0.0.1\tFALSE\t/\tTRUE\t0\tvisitor\t42\n",
	} {
		if !strings.Contains(written, want) {
			t.Errorf("the file has no %q:\n%s", want, written)
		}
	}
	if !strings.HasPrefix(written, "# Netscape HTTP Cookie File\n") {
		t.Errorf("no header:\n%s", written)
	}
}

func TestEncodeNetscapeDetails(t *testing.T) {
	set := Set{Cookies: []Cookie{
		// A leading dot is what this format uses to say "and everything under
		// it", which is the second column.
		{Name: "wide", Value: "1", Domain: ".example.com",
			Expires: time.Date(2030, 1, 2, 3, 4, 5, 0, time.UTC)},
		// No path given: a cookie without one belongs to the root.
		{Name: "narrow", Value: "2", Domain: "example.com"},
	}}
	written := string(set.EncodeNetscape())

	if !strings.Contains(written, ".example.com\tTRUE\t/\tFALSE\t1893553445\twide\t1\n") {
		t.Errorf("the wide cookie:\n%s", written)
	}
	if !strings.Contains(written, "example.com\tFALSE\t/\tFALSE\t0\tnarrow\t2\n") {
		t.Errorf("the narrow cookie:\n%s", written)
	}
}

func TestNetscapeRoundTrip(t *testing.T) {
	// Out and back through this project, and what comes back is what went in.
	original, err := Load([]byte(curlWrote))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	again, err := Load(original.Sets[0].EncodeNetscape())
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if len(again.Sets[0].Cookies) != len(original.Sets[0].Cookies) {
		t.Fatalf("%d cookies came back from %d", len(again.Sets[0].Cookies),
			len(original.Sets[0].Cookies))
	}
	for i, want := range original.Sets[0].Cookies {
		got := again.Sets[0].Cookies[i]
		if got.Name != want.Name || got.Value != want.Value || got.Domain != want.Domain ||
			got.Secure != want.Secure || got.HTTPOnly != want.HTTPOnly ||
			!got.Expires.Equal(want.Expires) {
			t.Errorf("cookie %d: got %+v, want %+v", i, got, want)
		}
	}
}

func TestLooksNetscape(t *testing.T) {
	// By content, not by the file's name: JSON starts with a brace or a bracket
	// and a cookies.txt never does, so there is nothing here to guess at.
	for body, want := range map[string]bool{
		"# Netscape HTTP Cookie File\n": true,
		"example.com\tTRUE\t/\t":        true,
		`{"sets":[]}`:                   false,
		`[{"name":"a"}]`:                false,
		"   \n\t {\"sets\":[]}":         false,
		"":                              false,
	} {
		if got := looksNetscape(body); got != want {
			t.Errorf("looksNetscape(%q) = %v, want %v", body, got, want)
		}
	}
}

func TestLoadNetscapeGivesUpOnAnEnormousLine(t *testing.T) {
	// A cookie file is lines, and a "line" that runs to megabytes is a file that
	// is not one. Reported rather than read as far as it fits.
	huge := "example.com\tTRUE\t/\tFALSE\t0\tname\t" + strings.Repeat("x", 5<<20) + "\n"
	if _, err := Load([]byte(huge)); err == nil {
		t.Error("no error")
	}
}
