#!/usr/bin/env node
// Generate the Homebrew formula for a release.
//
//   node scripts/homebrew-formula.mjs --version 0.1.0 --archives dist/release > dist/tls-forge.rb
//
// The formula installs a prebuilt binary rather than building from source. A
// source build would need Go and a network fetch of the module graph inside
// Homebrew's sandbox, which is slower and has more ways to fail; the binaries
// here are the same ones the release already built, tested and published to npm,
// so brew and npm hand out the identical artefact.
//
// Homebrew is pointed at tarballs rather than bare binaries on purpose: the
// licences of everything statically linked into the binary require their notices
// to travel with it, and a tarball is what carries them.

import { createHash } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const TARGETS = [
  { os: 'macos', cpu: 'arm', goos: 'darwin', goarch: 'arm64' },
  { os: 'macos', cpu: 'intel', goos: 'darwin', goarch: 'amd64' },
  { os: 'linux', cpu: 'arm', goos: 'linux', goarch: 'arm64' },
  { os: 'linux', cpu: 'intel', goos: 'linux', goarch: 'amd64' },
];

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  if (i >= 0 && process.argv[i + 1]) return process.argv[i + 1];
  if (fallback !== undefined) return fallback;
  throw new Error(`missing --${name}`);
}

const version = arg('version');
const archives = path.resolve(arg('archives', 'dist/release'));
const repo = 'Sec-CH-Lemon/tls-forge';

if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  throw new Error(`--version ${version} is not a semver version`);
}

/** archiveName is the release asset for a target, and must match release.yml. */
function archiveName(target) {
  return `tls-forge_${version}_${target.goos}_${target.goarch}.tar.gz`;
}

function sha256(file) {
  if (!existsSync(file)) throw new Error(`no archive at ${file}`);
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

const block = (target) => {
  const name = archiveName(target);
  return [
    `      url "https://github.com/${repo}/releases/download/v${version}/${name}"`,
    `      sha256 "${sha256(path.join(archives, name))}"`,
  ].join('\n');
};

const byOS = (os) =>
  TARGETS.filter((t) => t.os === os)
    .map((t) => `    on_${t.cpu} do\n${block(t)}\n    end`)
    .join('\n');

process.stdout.write(`# Generated by scripts/homebrew-formula.mjs. Do not edit by hand:
# the release workflow overwrites this file on every tag.
class TlsForge < Formula
  desc "Scraping HTTP client that sends a real browser's TLS fingerprint"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "Apache-2.0"

  on_macos do
${byOS('macos')}
  end

  on_linux do
${byOS('linux')}
  end

  def install
    bin.install "tls-forge"
    # Apache-2.0 section 4 and the licences of everything linked into the binary
    # require these to travel with it.
    pkgshare.install "LICENSE", "NOTICE", "THIRD-PARTY-NOTICES.txt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tls-forge version")

    # The point of the tool is the handshake it sends, so the test exercises it
    # rather than only checking that the binary runs. profiles reads the
    # embedded profile and prints what it can impersonate; it needs no network.
    assert_match "chrome", shell_output("#{bin}/tls-forge profiles")
  end
end
`);
