#!/bin/sh
# Regenerate THIRD-PARTY-NOTICES.txt from the module cache.
#
# This is not paperwork. The npm packages ship a compiled Go binary, and a Go
# binary is statically linked: every dependency below travels inside it. All of
# them are BSD- or MIT-style, and all of those licences require the copyright
# notice to accompany binary redistribution. So the notices have to be generated
# from what is actually linked, and regenerated when that changes.
#
#   ./scripts/notices.sh > THIRD-PARTY-NOTICES.txt
set -eu

cd "$(dirname "$0")/.."
module=$(go list -m)

cat <<EOF
THIRD-PARTY SOFTWARE NOTICES
============================

tls-forge compiles to a single static binary, so the software listed here is
linked into every copy of it that is distributed — including the binaries inside
the npm packages. Each licence below requires its copyright notice to travel
with that binary, which is why this file must travel with it too.

Generated by scripts/notices.sh. Regenerate it whenever the dependency set
changes; \`go list\` below is the source of truth, not this paragraph.

EOF

# Every module actually linked into the binary, as opposed to everything in
# go.sum: the test-only and tool dependencies are not redistributed.
go list -deps -f '{{if .Module}}{{.Module.Path}}{{"\t"}}{{.Module.Version}}{{"\t"}}{{.Module.Dir}}{{end}}' ./... |
  grep -v "^$module" | sort -u | while IFS="$(printf '\t')" read -r path version dir; do
    [ -n "$dir" ] || continue
    printf '\n%s\n%s %s\n%s\n\n' \
      "--------------------------------------------------------------------------------" \
      "$path" "$version" \
      "--------------------------------------------------------------------------------"

    licence=
    for candidate in "$dir"/*; do
      base=${candidate##*/}
      case $base in
        [Ll][Ii][Cc][Ee][Nn][Ss][Ee]*|[Ll][Ii][Cc][Ee][Nn][Cc][Ee]*|[Cc][Oo][Pp][Yy][Ii][Nn][Gg]*)
          licence=$base
          break
          ;;
      esac
    done
    if [ -n "$licence" ]; then
      cat "$dir/$licence"
    else
      # fhttp is the one module that ships no licence file. Its sources carry
      # the Go Authors' copyright header and it is a fork of net/http, so the
      # Go licence is the one that applies; it is reproduced here rather than
      # left as a gap.
      echo "This module ships no licence file. Its sources carry the header"
      echo "\"Copyright 2009 The Go Authors. All rights reserved. Use of this source"
      echo "code is governed by a BSD-style license\", and the module is a fork of"
      echo "the Go standard library's net/http. The Go licence therefore applies:"
      echo
      go_licence=$(go env GOROOT)/LICENSE
      [ -f "$go_licence" ] && cat "$go_licence"
    fi
  done
