"""The wire format, asserted against the same fixtures the Go daemon writes.

The rest of this suite runs against ``fake_daemon.py`` and never against the
real binary, so nothing in it would notice the Go side renaming a field. That
gap shipped once already: a renamed response field left every Python caller
receiving no cookies at all, with no exception and no warning, while ``go
test``, ``make node-test`` and ``make python-test`` were all green.

These fixtures are generated by ``go test ./daemon/ -run TestProtocolFixture
-update``. If one of these tests fails, the protocol changed — fix the client or
change the protocol deliberately, but do not regenerate the fixture to make the
test pass.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest

from tlsforge._client import _to_response

FIXTURES = Path(__file__).resolve().parents[2] / "testdata" / "protocol"

# The sdist ships these tests but not the repository's testdata/ directory, so
# they skip rather than fail when run from an unpacked release.
pytestmark = pytest.mark.skipif(
    not FIXTURES.is_dir(),
    reason="protocol fixtures are only present in a source checkout",
)


@pytest.fixture
def response_fixture() -> dict:
    return json.loads((FIXTURES / "response.json").read_text(encoding="utf-8"))


@pytest.fixture
def text_response_fixture() -> dict:
    return json.loads(
        (FIXTURES / "response-text.json").read_text(encoding="utf-8")
    )


@pytest.fixture
def request_fixture() -> dict:
    return json.loads((FIXTURES / "request.json").read_text(encoding="utf-8"))


def test_the_response_fixture_parses(response_fixture: dict) -> None:
    res = _to_response(response_fixture)
    assert res.status == 200
    assert res.url == "https://example.com/after-redirect"
    assert res.content == bytes([0x00, 0xFE, 0xFF, 0x80])
    assert res.headers["content-type"] == ("text/html; charset=utf-8",)
    assert res.headers["set-cookie"] == ("a=1", "b=2")
    # The field whose rename went unnoticed.
    assert res.cookies == ("a=1", "b=2")


def test_every_response_field_is_one_this_client_reads(response_fixture: dict) -> None:
    """A field the daemon sends and this client ignores is a feature nobody gets."""
    assert set(response_fixture) == {
        "id",
        "status",
        "url",
        "body",
        "bodyEncoding",
        "headers",
        "cookies",
    }


def test_a_text_response_keeps_the_legacy_shape_without_body_encoding(
    text_response_fixture: dict,
) -> None:
    assert "bodyEncoding" not in text_response_fixture
    res = _to_response(text_response_fixture)
    assert res.body == "plain text — unchanged"
    assert res.content == "plain text — unchanged".encode()


def test_the_request_fixture_is_the_shape_this_client_sends(
    request_fixture: dict,
) -> None:
    """The names this client puts on the wire, spelled out.

    Asserted against the fixture rather than against a hand-written list, so
    that renaming a request field in Go fails here too.
    """
    assert set(request_fixture) == {
        "id",
        "method",
        "url",
        "headers",
        "order",
        "body",
        "bodyEncoding",
        "setCookie",
    }
    assert request_fixture["bodyEncoding"] == "base64"
    assert base64.b64decode(request_fixture["body"]) == bytes([0x00, 0xFE, 0xFF, 0x80])
